ROBOT_NS:
  controller_manager:
    ros__parameters:
      update_rate: 50

      diffdrive_controller:
        type: diff_drive_controller/DiffDriveController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  diffdrive_controller:
    ros__parameters:
      left_wheel_names: ["left wheel motor"]
      right_wheel_names: ["right wheel motor"]

      wheel_separation: 0.11
      wheel_radius: 0.025

      # Bounding cylinder contact centres are ~5 mm inward from each hub (translation 0 0.005 0
      # in local frame), giving ~100 mm effective separation vs 110 mm hub separation.
      # 100/110 ≈ 0.909 corrects the angular velocity underestimation.
      wheel_separation_multiplier: 0.909

      use_stamped_vel: false
      base_frame_id: "base_link"
      odom_frame_id: "odom"
      enable_odom_tf: true

      linear:
        x:
          max_velocity: 0.5 # Maximal speed: matched to Webots motor maxVelocity (20 rad/s * 0.025 m)

  joint_state_broadcaster:
    ros__parameters:
      extra_joints:
        - LDS-01_secondary_motor
        - LDS-01_main_motor
